import PDFDocument from 'pdfkit';

function addSection(doc, title, items) {
  if (!items?.length) return;
  doc.moveDown(0.5).fontSize(12).fillColor('#008f7f').text(title);
  doc.fontSize(10).fillColor('#1a1a2e');
  items.forEach((item) => {
    if (typeof item === 'string') {
      doc.text(`• ${item}`, { indent: 10 });
    } else if (item?.name) {
      doc.text(`• ${item.name}${item.likelihood ? ` (${item.likelihood})` : ''}`, { indent: 10 });
      if (item.note) doc.text(`  ${item.note}`, { indent: 20 });
      if (item.usage) doc.text(`  Usage: ${item.usage}`, { indent: 20 });
      if (item.precaution) doc.text(`  Precaution: ${item.precaution}`, { indent: 20 });
    }
  });
}

export function buildConsultationPdf({ consultation, messages, summary, doctors }) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50, size: 'A4' });
    const chunks = [];

    doc.on('data', (chunk) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    doc.fontSize(20).fillColor('#00a896').text('BestechCare AI Doctor Consultation Report');
    doc.moveDown(0.3);
    doc.fontSize(10).fillColor('#6b7280').text(`Consultation ID: ${consultation.id}`);
    doc.text(`Date: ${new Date(consultation.created_at).toLocaleString()}`);
    if (consultation.completed_at) {
      doc.text(`Completed: ${new Date(consultation.completed_at).toLocaleString()}`);
    }

    doc.moveDown();
    doc.fontSize(11).fillColor('#1a1a2e').text(
      'DISCLAIMER: This report is generated by an AI assistant for informational purposes only. ' +
        'It does not replace professional medical advice, diagnosis, or treatment. ' +
        'Always consult a qualified healthcare provider.',
      { align: 'justify' }
    );

    if (summary?.summary) {
      doc.moveDown().fontSize(13).fillColor('#008f7f').text('Consultation Summary');
      doc.fontSize(10).fillColor('#1a1a2e').text(summary.summary, { align: 'justify' });
    }

    addSection(doc, 'Symptoms Discussed', summary?.symptoms_discussed);
    addSection(doc, 'Possible Conditions (not a diagnosis)', summary?.possible_conditions);
    addSection(doc, 'Suggested Medicines / Treatments', summary?.medicines);
    addSection(doc, 'Suggested Diagnostic Tests', summary?.suggested_tests);
    addSection(doc, 'Precautions', summary?.precautions);
    addSection(doc, 'Self-Care & Lifestyle', summary?.self_care);

    if (summary?.urgent_care_required) {
      doc.moveDown().fontSize(12).fillColor('#dc2626').text('⚠ URGENT MEDICAL ATTENTION RECOMMENDED');
      if (summary.urgent_care_reason) {
        doc.fontSize(10).text(summary.urgent_care_reason);
      }
    }

    if (doctors?.length) {
      doc.moveDown().fontSize(13).fillColor('#008f7f').text('Recommended Doctors on BestechCare');
      doc.fontSize(10).fillColor('#1a1a2e');
      doctors.slice(0, 5).forEach((d) => {
        doc.text(
          `• ${d.name} — ${d.specialty_name || d.specialty_slug} ` +
            `(Rating: ${d.rating || 'N/A'}, Fee: PKR ${d.consultation_fee || 0})`
        );
        if (d.hospital_name) doc.text(`  ${d.hospital_name}`, { indent: 10 });
      });
    }

    doc.moveDown().fontSize(13).fillColor('#008f7f').text('Full Conversation');
    doc.fontSize(9).fillColor('#374151');
    messages.forEach((m) => {
      const label = m.role === 'user' ? 'You' : 'AI Doctor';
      doc.moveDown(0.3).font('Helvetica-Bold').text(`${label}:`);
      doc.font('Helvetica').text(m.content, { align: 'justify' });
    });

    doc.moveDown();
    doc.fontSize(9).fillColor('#6b7280').text(
      summary?.disclaimer ||
        'Please book an appointment with a qualified doctor on BestechCare for professional evaluation.',
      { align: 'center' }
    );

    doc.end();
  });
}
